/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package cn.gsein.zjass.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static cn.gsein.zjass.psi.JassTypes.*;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Jass.flex</tt>
 */
public class JassLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int WAITING_STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
          0,  0,  1, 1
  };

  /**
   * Translates characters to character classes
   * Chosen bits are [12, 6, 3]
   * Total runtime size is 15760 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>9]<<6)|((ch>>3)&0x3f)]<<3)|(ch&0x7)];
  }

  /* The ZZ_CMAP_Z table has 2176 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
          "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1"+
                  "\20\1\21\1\22\3\21\1\23\1\24\1\25\1\21\14\26\1\27\50\26\1\30\2\26\1\31\1\32"+
                  "\1\33\1\34\25\26\1\35\20\21\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1"+
                  "\47\1\50\1\21\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\21\1\26\1\60\1\61\5\21"+
                  "\2\26\1\62\7\21\1\26\1\63\20\21\1\26\1\64\1\21\1\65\13\26\1\66\1\26\1\67\22"+
                  "\21\1\70\5\21\1\71\11\21\1\72\1\73\1\74\1\75\1\21\1\76\2\21\1\77\3\21\1\100"+
                  "\2\21\1\101\1\102\7\21\123\26\1\103\7\26\1\104\1\105\12\26\1\106\24\21\1\26"+
                  "\1\107\u0582\21\1\110\u017f\21");

  /* The ZZ_CMAP_Y table has 4672 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
          "\1\0\1\1\2\0\1\2\1\3\1\4\1\5\1\6\2\7\1\10\1\11\1\12\1\13\1\14\1\15\3\0\1\16"+
                  "\1\17\1\20\1\17\2\21\1\22\3\21\1\22\71\21\1\23\1\21\1\24\1\0\1\25\1\26\2\0"+
                  "\16\21\1\27\1\30\1\31\1\32\2\21\1\33\11\21\1\34\21\21\1\33\25\21\1\35\3\21"+
                  "\1\22\1\36\1\35\4\21\1\0\1\35\4\21\1\34\1\37\1\0\3\21\2\40\3\0\1\21\1\40\10"+
                  "\21\1\4\1\41\14\21\1\42\1\43\1\21\1\44\1\4\1\45\2\0\7\21\1\46\14\21\1\24\1"+
                  "\0\1\4\1\47\4\21\1\50\1\17\5\21\1\50\2\0\3\21\1\51\10\0\2\21\1\27\1\50\2\0"+
                  "\1\52\1\21\1\33\17\21\1\53\1\4\1\35\1\21\1\42\1\43\1\54\2\21\1\44\1\55\1\56"+
                  "\1\43\1\57\1\60\1\61\1\53\1\4\1\24\1\0\1\62\1\63\1\54\2\21\1\44\1\64\1\65"+
                  "\1\63\1\66\1\36\1\67\1\70\1\4\1\50\1\0\1\62\1\34\1\33\2\21\1\44\1\71\1\56"+
                  "\1\34\1\72\1\73\1\0\1\53\1\4\1\0\1\36\1\62\1\43\1\54\2\21\1\44\1\71\1\56\1"+
                  "\43\1\66\1\74\1\61\1\53\1\4\1\36\1\0\1\75\1\76\1\77\1\100\1\101\1\76\1\21"+
                  "\1\23\1\76\1\77\1\102\1\0\1\70\1\4\2\0\1\42\1\27\1\44\2\21\1\44\1\21\1\103"+
                  "\1\27\1\77\1\104\1\40\1\53\1\4\2\0\1\42\1\27\1\44\2\21\1\44\1\42\1\56\1\27"+
                  "\1\77\1\104\1\31\1\53\1\4\1\105\1\0\1\62\1\27\1\44\4\21\1\46\1\27\1\106\1"+
                  "\52\1\60\1\53\1\4\1\0\1\107\1\75\1\21\1\22\1\107\2\21\1\33\1\110\1\22\1\111"+
                  "\1\112\1\21\1\70\1\4\1\113\1\0\1\35\6\21\1\40\1\21\1\22\1\4\1\114\4\0\1\115"+
                  "\1\116\1\52\1\35\1\117\1\75\1\21\1\72\1\112\1\50\1\4\1\120\4\0\1\73\2\0\1"+
                  "\24\1\4\1\114\1\121\1\122\1\21\1\35\3\21\1\25\1\35\1\21\1\27\2\21\1\35\3\21"+
                  "\1\25\1\31\7\0\10\21\1\4\1\114\10\21\1\4\1\123\4\21\1\34\1\20\5\21\1\124\51"+
                  "\21\1\77\1\22\1\77\5\21\1\77\4\21\1\77\1\22\1\77\1\21\1\22\7\21\1\77\10\21"+
                  "\1\46\4\0\2\21\2\0\12\21\2\50\1\35\114\21\1\43\2\21\1\125\2\21\1\40\11\21"+
                  "\1\76\1\21\1\73\1\21\1\27\1\25\1\0\2\21\1\25\1\0\2\21\1\51\1\0\1\21\1\27\1"+
                  "\126\1\0\12\21\1\127\1\130\1\4\1\114\3\0\1\131\1\4\1\114\13\21\1\0\5\21\1"+
                  "\40\10\21\1\50\1\0\3\21\1\22\1\21\1\51\1\21\1\51\1\70\1\4\3\21\1\50\1\25\1"+
                  "\0\5\21\1\51\3\21\1\24\1\4\1\114\4\0\3\21\1\51\7\21\1\22\3\21\1\43\1\4\1\114"+
                  "\1\4\1\114\1\60\1\0\1\21\1\22\10\0\11\21\1\51\1\4\1\114\1\0\1\132\1\51\1\0"+
                  "\6\21\1\4\1\47\6\21\1\51\1\0\7\21\1\0\1\4\1\133\1\4\1\47\3\21\1\50\1\21\1"+
                  "\73\10\0\1\124\3\21\1\22\1\24\36\21\1\50\1\132\42\21\2\50\4\21\2\50\1\21\1"+
                  "\134\3\21\1\50\6\21\1\27\1\112\1\135\1\25\1\136\1\51\1\21\1\25\1\135\1\25"+
                  "\1\137\1\140\3\0\1\141\1\0\1\60\1\73\1\0\1\142\1\143\2\0\1\36\1\60\2\0\1\21"+
                  "\1\25\6\0\4\21\1\73\1\0\1\111\1\107\1\110\1\144\1\26\1\145\1\21\1\56\1\146"+
                  "\1\147\2\0\5\21\1\73\144\0\1\74\6\21\1\24\42\0\5\21\1\22\5\21\1\22\20\21\1"+
                  "\25\1\132\1\51\1\0\4\21\1\34\1\20\7\21\1\60\1\0\1\60\2\21\1\22\1\0\10\22\4"+
                  "\21\5\0\1\60\72\0\1\150\3\0\1\35\1\21\1\144\1\25\1\35\11\21\1\22\1\151\1\35"+
                  "\12\21\1\124\1\146\4\21\1\50\1\35\12\21\1\22\2\0\3\21\1\40\6\0\170\21\1\50"+
                  "\11\0\72\21\1\50\5\0\21\21\1\25\10\0\5\21\1\50\41\21\1\25\2\21\1\4\1\152\2"+
                  "\0\6\21\1\124\1\34\16\21\1\24\3\0\1\60\1\21\1\107\14\21\1\54\3\21\1\22\1\21"+
                  "\7\0\1\60\6\21\3\0\6\21\1\51\1\0\10\21\1\50\1\0\1\4\1\114\3\21\1\153\1\4\1"+
                  "\47\3\21\1\50\4\21\1\51\1\0\3\21\1\25\10\21\1\73\1\60\1\4\1\114\2\21\1\4\1"+
                  "\154\6\21\1\22\1\0\1\21\1\50\1\4\1\114\2\21\1\22\1\107\10\21\1\40\2\0\1\131"+
                  "\2\21\1\155\1\0\3\156\1\0\2\22\5\21\1\124\1\50\1\0\17\21\1\157\1\4\1\114\64"+
                  "\21\1\51\1\0\2\21\1\22\1\132\5\21\1\51\40\0\55\21\1\50\15\21\1\24\4\0\1\22"+
                  "\1\0\1\132\1\146\1\21\1\44\1\22\1\112\1\160\15\21\1\24\3\0\1\132\54\21\1\50"+
                  "\2\0\10\21\1\107\6\21\5\0\1\21\1\51\2\21\2\0\2\21\1\101\2\0\1\146\4\0\1\27"+
                  "\20\21\1\25\2\0\1\4\1\114\1\35\2\21\1\63\1\35\2\21\1\40\1\74\12\21\1\22\3"+
                  "\107\1\161\4\0\1\21\1\42\2\21\1\22\2\21\1\162\1\21\1\50\1\21\1\50\4\0\17\21"+
                  "\1\40\10\0\6\21\1\25\20\0\1\20\20\0\3\21\1\25\6\21\1\73\1\0\1\73\3\0\4\21"+
                  "\2\0\3\21\1\40\5\21\1\40\3\21\1\50\4\21\1\51\1\21\1\144\5\0\23\21\1\50\1\4"+
                  "\1\114\4\21\1\51\4\21\1\51\5\21\1\0\6\21\1\51\23\0\46\21\1\22\1\0\2\21\1\50"+
                  "\1\0\1\21\23\0\1\50\1\44\4\21\1\34\1\163\2\21\1\50\1\0\2\21\1\22\1\0\3\21"+
                  "\1\22\10\0\2\21\1\157\1\0\2\21\1\50\1\0\3\21\1\24\10\0\7\21\1\74\10\0\1\164"+
                  "\1\52\1\42\1\35\2\21\1\51\1\63\4\0\3\21\1\25\3\21\1\25\4\0\1\21\1\35\2\21"+
                  "\1\22\3\0\6\21\1\50\1\0\2\21\1\50\1\0\2\21\1\40\1\0\2\21\1\24\15\0\11\21\1"+
                  "\73\6\0\6\21\1\40\1\0\6\21\1\40\41\0\10\21\1\22\3\0\1\70\1\4\1\0\1\60\7\21"+
                  "\1\40\2\0\3\21\1\73\1\4\1\114\6\21\1\165\1\4\2\0\4\21\1\166\1\0\10\21\1\25"+
                  "\1\161\1\4\1\167\4\0\2\21\1\33\4\21\1\31\10\0\1\22\1\145\1\21\1\34\1\21\1"+
                  "\73\7\21\1\40\1\4\1\114\1\42\1\43\1\54\2\21\1\44\1\71\1\56\1\43\1\66\1\102"+
                  "\1\146\1\136\2\25\21\0\11\21\1\40\1\4\1\114\4\0\10\21\1\34\1\0\1\4\1\114\24"+
                  "\0\6\21\1\50\1\21\1\73\2\0\1\50\4\0\10\21\1\170\1\0\1\4\1\114\4\0\7\21\1\0"+
                  "\1\4\1\114\6\0\3\21\1\103\1\21\1\51\1\4\1\114\54\0\10\21\1\4\1\114\1\0\1\60"+
                  "\70\0\7\21\1\73\40\0\1\21\1\44\4\21\1\22\1\21\1\73\1\0\1\4\1\114\2\0\1\107"+
                  "\3\21\1\107\2\21\1\35\1\22\51\0\63\21\1\24\14\0\15\21\1\22\2\0\30\21\1\51"+
                  "\27\0\5\21\1\22\72\0\10\21\1\22\67\0\7\21\1\73\3\21\1\22\1\4\1\114\14\0\3"+
                  "\21\1\50\1\25\1\0\6\21\1\22\1\0\1\51\1\0\1\4\1\114\1\132\2\21\1\146\2\21\56"+
                  "\0\10\21\1\25\1\0\5\21\1\22\1\0\1\60\2\21\10\0\1\73\3\0\75\21\1\25\2\0\36"+
                  "\21\1\40\41\0\1\24\77\0\15\21\1\40\1\21\1\25\1\21\1\73\1\21\1\171\130\0\1"+
                  "\146\1\103\1\40\1\132\1\46\1\51\3\0\1\172\22\0\1\161\67\0\12\21\1\27\10\21"+
                  "\1\27\1\173\1\174\1\21\1\175\1\42\7\21\1\34\1\46\2\27\3\21\1\176\1\112\1\107"+
                  "\1\44\51\21\1\50\3\21\1\44\2\21\1\124\3\21\1\124\2\21\1\27\3\21\1\27\2\21"+
                  "\1\22\3\21\1\22\3\21\1\44\3\21\1\44\2\21\1\124\1\53\6\4\6\21\1\22\1\132\5"+
                  "\21\1\25\1\20\1\0\1\142\2\0\1\132\1\35\1\21\52\0\1\22\2\21\1\54\1\160\1\40"+
                  "\72\0\30\21\1\25\1\0\1\22\5\0\11\21\1\40\1\4\1\114\24\0\1\42\3\21\1\115\1"+
                  "\35\1\124\1\177\1\111\1\200\1\115\1\134\1\115\2\124\1\67\1\21\1\33\1\21\1"+
                  "\51\1\62\1\33\1\21\1\51\116\0\3\21\1\24\3\21\1\24\3\21\1\24\16\0\32\21\1\22"+
                  "\5\0\106\21\1\25\1\0\33\21\1\50\120\21\1\24\53\0\3\21\1\50\134\0\36\21\2\0");

  /* The ZZ_CMAP_A table has 1032 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
          "\11\0\1\2\4\1\2\0\1\2\1\0\1\5\5\0\1\35\1\36\1\7\1\32\1\37\1\34\1\4\1\6\12"+
                  "\3\2\0\1\47\1\31\1\46\2\0\22\10\4\0\1\10\1\0\1\20\1\26\1\27\1\24\1\15\1\45"+
                  "\1\16\1\44\1\12\1\10\1\43\1\21\1\23\1\13\1\25\1\40\1\10\1\17\1\22\1\14\1\33"+
                  "\1\42\1\50\1\41\1\30\1\10\12\0\1\1\2\0\1\2\11\0\1\11\12\0\1\11\2\0\17\11\1"+
                  "\0\2\11\4\0\4\11\6\0\5\11\7\0\1\11\1\0\1\11\1\0\5\11\1\0\2\11\2\0\4\11\1\0"+
                  "\1\11\6\0\1\11\1\0\3\11\1\0\1\11\1\0\4\11\1\0\13\11\1\0\1\11\1\0\7\11\1\0"+
                  "\1\11\7\0\2\11\1\0\2\11\1\0\4\11\5\0\2\3\4\0\6\11\1\0\10\11\2\0\2\11\1\0\6"+
                  "\11\2\3\3\11\2\0\4\11\2\0\3\11\2\3\14\11\2\0\4\11\10\0\10\11\2\0\2\3\1\11"+
                  "\2\0\6\11\1\0\1\11\3\0\4\11\2\0\5\11\2\0\4\11\10\0\1\11\4\0\2\11\1\0\1\11"+
                  "\1\0\3\11\1\0\6\11\4\0\2\11\1\0\2\11\1\0\2\11\1\0\2\11\2\0\1\11\1\0\3\11\2"+
                  "\0\3\11\3\0\4\11\1\0\1\11\7\0\2\3\1\11\1\0\2\11\1\0\5\11\1\0\3\11\2\0\1\11"+
                  "\15\0\2\11\2\0\2\11\1\0\6\11\3\0\3\11\1\0\4\11\3\0\2\11\1\0\1\11\1\0\2\11"+
                  "\3\0\2\11\3\0\1\11\6\0\3\11\3\0\3\11\5\0\2\11\2\0\2\11\5\0\1\11\1\0\5\11\3"+
                  "\0\12\11\1\0\1\11\4\0\1\11\4\0\6\11\1\0\1\11\3\0\2\11\4\0\2\3\7\0\2\11\1\0"+
                  "\1\11\2\0\2\11\1\0\1\11\2\0\1\11\3\0\3\11\1\0\1\11\1\0\1\11\2\3\2\0\4\11\5"+
                  "\0\1\11\1\0\1\11\1\0\1\11\4\0\2\11\2\3\4\11\2\0\3\11\1\0\4\11\1\2\10\11\1"+
                  "\0\2\11\4\0\4\11\3\0\1\11\4\0\2\11\5\0\3\11\5\0\5\11\2\3\3\0\3\11\1\0\1\11"+
                  "\1\0\1\11\1\0\1\11\1\0\1\11\2\0\3\11\1\0\6\11\2\0\2\11\13\2\5\0\2\1\5\0\1"+
                  "\2\4\0\1\11\12\0\1\2\1\0\5\11\2\0\1\11\1\0\4\11\1\0\1\11\5\0\5\11\4\0\1\11"+
                  "\1\0\1\2\4\0\3\11\1\0\2\11\2\0\3\11\2\3\2\11\7\0\1\11\1\0\1\11\2\0\2\3\5\11"+
                  "\3\0\5\11\2\0\6\11\1\0\3\11\1\0\2\11\2\0\2\11\1\0\2\11\1\0\2\11\2\0\3\11\3"+
                  "\0\3\11\1\0\2\11\1\0\2\11\3\0\1\11\2\0\5\11\1\0\2\11\1\0\5\11\1\0\2\3\4\11"+
                  "\2\0\1\11\1\0\2\3\1\11\1\0\1\11\3\0\1\11\3\0\1\11\3\0\2\11\3\0\2\11\3\0\4"+
                  "\11\4\0\1\11\2\0\2\11\2\0\4\11\1\0\4\11\1\0\1\11\1\0\5\11\1\0\4\11\2\0\1\11"+
                  "\1\0\1\11\5\0\1\11\1\0\1\11\1\0\3\11");

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
          "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
                  "\13\10\1\11\1\12\1\13\1\14\1\15\1\16\1\10"+
                  "\1\17\1\20\1\1\1\21\1\22\1\23\1\0\1\10"+
                  "\1\24\23\10\1\25\1\10\1\26\1\27\2\0\24\10"+
                  "\1\30\3\10\1\0\1\31\3\10\1\32\2\10\1\33"+
                  "\1\34\4\10\1\35\4\10\1\36\1\10\1\37\2\10"+
                  "\1\40\5\10\1\36\1\41\1\42\10\10\1\43\1\44"+
                  "\4\10\1\45\5\10\1\46\3\10\1\47\2\10\1\50"+
                  "\2\10\1\51\2\10\1\52\1\53\1\54\5\10\1\55"+
                  "\1\56\1\57\3\10\1\60\1\10\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
          "\0\0\0\51\0\122\0\173\0\244\0\122\0\315\0\122"+
                  "\0\366\0\u011f\0\u0148\0\u0171\0\u019a\0\u01c3\0\u01ec\0\u0215"+
                  "\0\u023e\0\u0267\0\u0290\0\u02b9\0\122\0\122\0\122\0\122"+
                  "\0\122\0\u02e2\0\u030b\0\u0334\0\u035d\0\122\0\u0386\0\u03af"+
                  "\0\u03d8\0\u0401\0\366\0\u042a\0\u0453\0\u047c\0\u04a5\0\u04ce"+
                  "\0\u04f7\0\u0520\0\u0549\0\u0572\0\u059b\0\u05c4\0\u05ed\0\u0616"+
                  "\0\u063f\0\u0668\0\u0691\0\u06ba\0\u06e3\0\u070c\0\122\0\u0735"+
                  "\0\122\0\122\0\u075e\0\u0787\0\u07b0\0\u07d9\0\u0802\0\u082b"+
                  "\0\u0854\0\u087d\0\u08a6\0\u08cf\0\u08f8\0\u0921\0\u094a\0\u0973"+
                  "\0\u099c\0\u09c5\0\u09ee\0\u0a17\0\u0a40\0\u0a69\0\u0a92\0\u0abb"+
                  "\0\366\0\u0ae4\0\u0b0d\0\u0b36\0\u0b5f\0\122\0\u0b88\0\u0bb1"+
                  "\0\u0bda\0\366\0\u0c03\0\u0c2c\0\366\0\366\0\u0c55\0\u0c7e"+
                  "\0\u0ca7\0\u0cd0\0\u0cf9\0\u0d22\0\u0d4b\0\u0d74\0\u0d9d\0\366"+
                  "\0\u0dc6\0\366\0\u0def\0\u0e18\0\366\0\u0e41\0\u0e6a\0\u0e93"+
                  "\0\u0ebc\0\u0ee5\0\u0f0e\0\366\0\366\0\u0f37\0\u0f60\0\u0f89"+
                  "\0\u0fb2\0\u0fdb\0\u1004\0\u102d\0\u1056\0\366\0\366\0\u107f"+
                  "\0\u10a8\0\u10d1\0\u10fa\0\366\0\u1123\0\u114c\0\u1175\0\u119e"+
                  "\0\u11c7\0\366\0\u11f0\0\u1219\0\u1242\0\u126b\0\u1294\0\u12bd"+
                  "\0\366\0\u12e6\0\u130f\0\366\0\u1338\0\u1361\0\366\0\366"+
                  "\0\366\0\u138a\0\u13b3\0\u13dc\0\u1405\0\u142e\0\366\0\366"+
                  "\0\366\0\u1457\0\u1480\0\u14a9\0\366\0\u14d2\0\366";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
          "\1\3\2\4\1\5\1\3\1\6\1\7\1\10\1\11"+
                  "\1\3\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
                  "\1\21\1\22\4\11\1\23\1\11\1\24\1\25\1\11"+
                  "\1\26\1\27\1\30\1\31\5\11\1\32\1\33\1\34"+
                  "\1\11\5\35\1\36\43\35\52\0\2\4\51\0\1\5"+
                  "\1\37\52\0\1\40\1\41\44\0\1\11\4\0\21\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\3\11\1\42\15\11\2\0\1\11\4\0\5\11"+
                  "\1\43\2\0\1\11\3\0\1\11\4\0\10\11\1\44"+
                  "\4\11\1\45\3\11\2\0\1\46\4\0\6\11\2\0"+
                  "\1\11\3\0\1\11\4\0\2\11\1\47\4\11\1\50"+
                  "\1\51\7\11\1\52\2\0\1\11\4\0\4\11\1\53"+
                  "\1\11\2\0\1\11\3\0\1\11\4\0\3\11\1\54"+
                  "\5\11\1\55\7\11\2\0\1\11\4\0\1\11\1\56"+
                  "\4\11\2\0\1\11\3\0\1\11\4\0\11\11\1\57"+
                  "\7\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\5\11\1\60\13\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\11\3\0\1\11\4\0\7\11\1\61"+
                  "\11\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\15\11\1\62\3\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\11\3\0\1\11\4\0\4\11\1\63"+
                  "\1\64\13\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\10\11\1\65\4\11\1\66\3\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\31\0\1\67"+
                  "\22\0\1\11\4\0\21\11\2\0\1\70\4\0\6\11"+
                  "\2\0\1\11\31\0\1\71\50\0\1\72\17\0\5\35"+
                  "\1\0\43\35\3\0\1\37\45\0\1\40\1\0\47\40"+
                  "\7\73\1\74\41\73\3\0\1\11\4\0\4\11\1\75"+
                  "\14\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\4\11\1\76\14\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\11\3\0\1\11\4\0\4\11\1\77"+
                  "\14\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\11\11\1\100\7\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\11\3\0\1\11\4\0\13\11\1\101"+
                  "\5\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\2\11\1\102\16\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\11\3\0\1\11\4\0\21\11\2\0"+
                  "\1\11\4\0\3\11\1\103\2\11\2\0\1\11\3\0"+
                  "\1\11\4\0\21\11\2\0\1\11\4\0\1\104\5\11"+
                  "\2\0\1\11\3\0\1\11\4\0\5\11\1\105\13\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\14\11\1\106\4\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\12\11\1\107\6\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\2\11\1\110\1\11\1\111\14\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\15\11"+
                  "\1\112\3\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\4\11\1\113\3\11\1\114\10\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\7\11\1\115\11\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\15\11\1\116\1\11"+
                  "\1\117\1\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\7\11\1\120\11\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\4\11"+
                  "\1\121\14\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\11\11\1\122\7\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\3\11"+
                  "\1\123\15\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\3\11\1\124\15\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\7\73\1\125\41\73\6\0"+
                  "\1\126\1\74\44\0\1\11\4\0\5\11\1\127\13\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\2\11\1\130\16\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\21\11\2\0\1\11"+
                  "\4\0\4\11\1\131\1\11\2\0\1\11\3\0\1\11"+
                  "\4\0\11\11\1\132\7\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\5\11\1\133\13\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\6\11\1\127\12\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\5\11\1\134\13\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\5\11\1\135\13\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\3\11\1\136\15\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\2\11\1\137\3\11\1\140\2\11\1\141\7\11"+
                  "\2\0\1\11\4\0\5\11\1\142\2\0\1\11\3\0"+
                  "\1\11\4\0\5\11\1\143\13\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\11\3\0\1\11\4\0\4\11\1\144"+
                  "\14\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\5\11\1\145\13\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\11\3\0\1\11\4\0\16\11\1\146"+
                  "\2\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\21\11\2\0\1\147\4\0\6\11\2\0"+
                  "\1\11\3\0\1\11\4\0\11\11\1\150\7\11\2\0"+
                  "\1\11\4\0\6\11\2\0\1\11\3\0\1\11\4\0"+
                  "\10\11\1\151\10\11\2\0\1\11\4\0\6\11\2\0"+
                  "\1\11\3\0\1\11\4\0\21\11\2\0\1\11\4\0"+
                  "\1\152\5\11\2\0\1\11\3\0\1\11\4\0\10\11"+
                  "\1\153\10\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\2\11\1\154\16\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\11\11"+
                  "\1\155\7\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\12\11\1\156\6\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\17\11"+
                  "\1\157\1\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\6\73\1\126\1\125\41\73\3\0\1\11\4\0\6\11"+
                  "\1\160\12\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\21\11\2\0\1\11\4\0\2\11"+
                  "\1\161\3\11\2\0\1\11\3\0\1\11\4\0\2\11"+
                  "\1\162\16\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\7\11\1\163\11\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\12\11"+
                  "\1\164\6\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\21\11\2\0\1\11\4\0\5\11"+
                  "\1\165\2\0\1\11\3\0\1\11\4\0\11\11\1\166"+
                  "\7\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\15\11\1\167\3\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\11\3\0\1\11\4\0\21\11\2\0"+
                  "\1\170\4\0\6\11\2\0\1\11\3\0\1\11\4\0"+
                  "\2\11\1\171\16\11\2\0\1\11\4\0\6\11\2\0"+
                  "\1\11\3\0\1\11\4\0\21\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\172\3\0\1\11\4\0\3\11\1\173"+
                  "\15\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\10\11\1\174\10\11\2\0\1\11\4\0"+
                  "\6\11\2\0\1\11\3\0\1\11\4\0\7\11\1\175"+
                  "\11\11\2\0\1\11\4\0\6\11\2\0\1\11\3\0"+
                  "\1\11\4\0\20\11\1\176\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\11\11\1\177\7\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\3\11\1\200\15\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\4\11\1\201\14\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\4\11\1\202\14\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\5\11\1\203\13\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\5\11\1\204\13\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\3\11\1\205\15\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\14\11\1\206\4\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\15\11\1\207\3\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\15\11\1\210\3\11\2\0\1\11\4\0\6\11"+
                  "\2\0\1\11\3\0\1\11\4\0\3\11\1\211\15\11"+
                  "\2\0\1\11\4\0\6\11\2\0\1\11\3\0\1\11"+
                  "\4\0\21\11\2\0\1\11\4\0\5\11\1\212\2\0"+
                  "\1\11\3\0\1\11\4\0\21\11\2\0\1\11\4\0"+
                  "\4\11\1\213\1\11\2\0\1\11\3\0\1\11\4\0"+
                  "\14\11\1\214\4\11\2\0\1\11\4\0\6\11\2\0"+
                  "\1\11\3\0\1\11\4\0\11\11\1\215\7\11\2\0"+
                  "\1\11\4\0\6\11\2\0\1\11\3\0\1\11\4\0"+
                  "\3\11\1\216\15\11\2\0\1\11\4\0\6\11\2\0"+
                  "\1\11\3\0\1\11\4\0\6\11\1\150\12\11\2\0"+
                  "\1\11\4\0\6\11\2\0\1\11\3\0\1\11\4\0"+
                  "\10\11\1\217\10\11\2\0\1\11\4\0\6\11\2\0"+
                  "\1\11\3\0\1\11\4\0\2\11\1\220\16\11\2\0"+
                  "\1\11\4\0\6\11\2\0\1\11\3\0\1\11\4\0"+
                  "\7\11\1\150\11\11\2\0\1\11\4\0\6\11\2\0"+
                  "\1\11\3\0\1\11\4\0\6\11\1\221\12\11\2\0"+
                  "\1\11\4\0\6\11\2\0\1\11\3\0\1\11\4\0"+
                  "\2\11\1\222\16\11\2\0\1\11\4\0\6\11\2\0"+
                  "\1\11\3\0\1\11\4\0\16\11\1\223\2\11\2\0"+
                  "\1\11\4\0\6\11\2\0\1\11\3\0\1\11\4\0"+
                  "\21\11\2\0\1\11\4\0\1\224\5\11\2\0\1\11"+
                  "\3\0\1\11\4\0\17\11\1\225\1\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\5\11"+
                  "\1\226\13\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\12\11\1\227\6\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\12\11"+
                  "\1\230\6\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\12\11\1\231\6\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\3\11"+
                  "\1\232\15\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\15\11\1\233\3\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\10\11"+
                  "\1\234\10\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\10\11\1\235\10\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\4\11"+
                  "\1\236\14\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\3\11\1\237\15\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\4\11"+
                  "\1\240\14\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\3\11\1\241\15\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\11\11"+
                  "\1\242\7\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\11\11\1\243\7\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\2\11"+
                  "\1\244\16\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\15\11\1\200\3\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\12\11"+
                  "\1\245\6\11\2\0\1\11\4\0\6\11\2\0\1\11"+
                  "\3\0\1\11\4\0\15\11\1\246\3\11\2\0\1\11"+
                  "\4\0\6\11\2\0\1\11\3\0\1\11\4\0\3\11"+
                  "\1\247\15\11\2\0\1\11\4\0\6\11\2\0\1\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5371];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
          "Unknown internal scanner error",
          "Error: could not match input",
          "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
          "\1\0\1\1\1\11\2\1\1\11\1\1\1\11\14\1"+
                  "\5\11\4\1\1\11\2\1\1\0\25\1\1\11\1\1"+
                  "\2\11\2\0\30\1\1\0\1\11\121\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
   the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
   from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public JassLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JassLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /**
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
          { return STRING_CONST;
          }
          // fall through
          case 50: break;
          case 2:
          { return BAD_CHARACTER;
          }
          // fall through
          case 51: break;
          case 3:
          { return WHITE_SPACE;
          }
          // fall through
          case 52: break;
          case 4:
          { return INTEGER_CONST;
          }
          // fall through
          case 53: break;
          case 5:
          { yybegin(WAITING_STRING); return DOUBLE_QUOTE;
          }
          // fall through
          case 54: break;
          case 6:
          { return DIV;
          }
          // fall through
          case 55: break;
          case 7:
          { return MUL;
          }
          // fall through
          case 56: break;
          case 8:
          { return ID;
          }
          // fall through
          case 57: break;
          case 9:
          { return EQ;
          }
          // fall through
          case 58: break;
          case 10:
          { return PLUS;
          }
          // fall through
          case 59: break;
          case 11:
          { return MINUS;
          }
          // fall through
          case 60: break;
          case 12:
          { return LPAREN;
          }
          // fall through
          case 61: break;
          case 13:
          { return RPAREN;
          }
          // fall through
          case 62: break;
          case 14:
          { return COLON;
          }
          // fall through
          case 63: break;
          case 15:
          { return GT;
          }
          // fall through
          case 64: break;
          case 16:
          { return LT;
          }
          // fall through
          case 65: break;
          case 17:
          { yybegin(YYINITIAL); return DOUBLE_QUOTE;
          }
          // fall through
          case 66: break;
          case 18:
          { return REAL_CONST;
          }
          // fall through
          case 67: break;
          case 19:
          { return EOL_COMMENT;
          }
          // fall through
          case 68: break;
          case 20:
          { return IF;
          }
          // fall through
          case 69: break;
          case 21:
          { return DOUBLE_EQ;
          }
          // fall through
          case 70: break;
          case 22:
          { return GE;
          }
          // fall through
          case 71: break;
          case 23:
          { return LE;
          }
          // fall through
          case 72: break;
          case 24:
          { return SET;
          }
          // fall through
          case 73: break;
          case 25:
          { return MUL_COMMENT;
          }
          // fall through
          case 74: break;
          case 26:
          { return NULL;
          }
          // fall through
          case 75: break;
          case 27:
          { return TYPE;
          }
          // fall through
          case 76: break;
          case 28:
          { return THEN;
          }
          // fall through
          case 77: break;
          case 29:
          { return ELSE;
          }
          // fall through
          case 78: break;
          case 30:
          { return TYPE_ID;
          }
          // fall through
          case 79: break;
          case 31:
          { return LOOP;
          }
          // fall through
          case 80: break;
          case 32:
          { return CALL;
          }
          // fall through
          case 81: break;
          case 33:
          { return TAKES;
          }
          // fall through
          case 82: break;
          case 34:
          { return ENDIF;
          }
          // fall through
          case 83: break;
          case 35:
          { return ARRAY;
          }
          // fall through
          case 84: break;
          case 36:
          { return LOCAL;
          }
          // fall through
          case 85: break;
          case 37:
          { return NATIVE;
          }
          // fall through
          case 86: break;
          case 38:
          { return ELSEIF;
          }
          // fall through
          case 87: break;
          case 39:
          { return RETURN;
          }
          // fall through
          case 88: break;
          case 40:
          { return NOTHING;
          }
          // fall through
          case 89: break;
          case 41:
          { return ENDLOOP;
          }
          // fall through
          case 90: break;
          case 42:
          { return EXTENDS;
          }
          // fall through
          case 91: break;
          case 43:
          { return GLOBALS;
          }
          // fall through
          case 92: break;
          case 44:
          { return RETURNS;
          }
          // fall through
          case 93: break;
          case 45:
          { return EXITWHEN;
          }
          // fall through
          case 94: break;
          case 46:
          { return CONSTANT;
          }
          // fall through
          case 95: break;
          case 47:
          { return FUNCTION;
          }
          // fall through
          case 96: break;
          case 48:
          { return ENDGLOBALS;
          }
          // fall through
          case 97: break;
          case 49:
          { return ENDFUNCTION;
          }
          // fall through
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
